[package]
name = "rustdash"
version = "1.0.1"
edition = "2021"

[lib]
name = "rustdash"
crate-type = ["cdylib", "rlib"]

[dependencies]
fancy-regex = "0.17.0"
pyo3 = { version = "0.23", features = ["extension-module", "generate-import-lib"] }
regex = "1.12.2"
